# Generated by Django 5.1.1 on 2024-09-20 20:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_created_at_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
