# Generated by Django 5.1.1 on 2024-09-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_uid_alter_product_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
