# Generated by Django 5.1.1 on 2024-09-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_category_alter_product_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_seen', 'price'], name='products_pr_is_seen_4a4627_idx'),
        ),
    ]
