# Generated by Django 5.1.1 on 2024-09-25 19:43

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_products_pr_is_seen_4a4627_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('price')), name='tatal_amount_idx'),
        ),
    ]
